#!/usr/bin/env python3
"""Generate docs/skills/index.md from skills/*/SKILL.md.

Single source of truth: the skill catalogue on the site is derived from the skills
themselves, so agents, developers, and CI never hand-maintain a duplicate list.

Each SKILL.md provides `name` and `description` in YAML frontmatter, and optionally a
`<!-- doc: <path> -->` marker pointing at its canonical guide page.
"""
from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SKILLS_DIR = ROOT / "skills"
OUT = ROOT / "docs" / "skills" / "index.md"

FRONTMATTER = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)
DOC_MARKER = re.compile(r"<!--\s*doc:\s*(?P<doc>\S+)\s*-->")


def field(block: str, key: str) -> str:
    m = re.search(rf"^{key}:\s*(.+?)\s*$", block, re.MULTILINE)
    return m.group(1).strip().strip('"').strip("'") if m else ""


def parse(skill_md: pathlib.Path) -> dict:
    text = skill_md.read_text(encoding="utf-8")
    fm = FRONTMATTER.search(text)
    block = fm.group(1) if fm else ""
    doc = DOC_MARKER.search(text)
    return {
        "name": field(block, "name") or skill_md.parent.name,
        "description": field(block, "description"),
        "dir": skill_md.parent.relative_to(ROOT).as_posix(),
        "doc": doc.group("doc") if doc else "",
    }


def main() -> int:
    skills = sorted(
        (parse(p) for p in SKILLS_DIR.glob("*/SKILL.md")),
        key=lambda s: s["name"],
    )

    lines = [
        "# Skills",
        "",
        "AI-ready skills that create and maintain Linear work to the documented",
        "operating model. Install them as a Claude Code plugin, then invoke by name.",
        "",
        "```text",
        "/plugin marketplace add dataGriff/linear-work-management",
        "/plugin install linear-work-management@linear-work-management",
        "```",
        "",
        "**Prerequisite:** these skills act on your Linear workspace through the **Linear MCP",
        "server** — connect it before using them.",
        "",
        "<!-- Generated by scripts/gen_skill_index.py — do not edit by hand. -->",
        "",
        "| Skill | What it does | Guide |",
        "| ----- | ------------ | ----- |",
    ]
    for s in skills:
        guide = f"[{s['doc'].split('/')[-1].replace('.md','')}](../{s['doc']})" if s["doc"] else "—"
        src = f"[`{s['name']}`](https://github.com/dataGriff/linear-work-management/tree/main/{s['dir']})"
        lines.append(f"| {src} | {s['description']} | {guide} |")

    lines.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(skills)} skill(s)).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
